export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  BOOKS: '/books',
  BOOK_DETAILS: '/books/:id',
  BOOK_READ: '/books/:id/read',
  SEARCH: '/search',
  WRITERS: '/writers',
  LIBRARY: '/library',
  PURCHASES: '/purchases',
  PROFILE: '/profile',
  WRITER_DASHBOARD: '/writer/dashboard',
  WRITER_BOOKS: '/writer/books',
  WRITER_CREATE_BOOK: '/writer/create-book',
  WRITER_EDIT_BOOK: '/writer/edit-book/:id',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_USERS: '/admin/users',
  ADMIN_BOOKS: '/admin/books',
  ADMIN_REVIEWS: '/admin/reviews',
  CHECKOUT: '/checkout/:id',
};
