spring:
  application:
    name: bookverse-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://prachimehar841:Prachi841@cluster0.de5zju5.mongodb.net/bookverse?retryWrites=true&w=majority}
    serialization:
      INDENT_OUTPUT: true

server:
  port: ${PORT:8080}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173,https://bookverse.vercel.app}

jwt:
  secret: ${JWT_SECRET:adgcQwqH1pGrtshu4MON0WAiyB6S57XmfkRxZbPn}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
  issuer: bookverse

google:
  client-id: ${GOOGLE_CLIENT_ID:502840310207-lostkpb3ct42m7cc9hr54o9cbd322vm1.apps.googleusercontent.com}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
